### ISSUE TITLE
Week 5: Exercise 2

### ISSUE THREAD

**Issue by Futsy** [bgrevelt/PT_MA1_3#8]
In lab assignment 2 they state:

> "Refactor the code along the lines of this proposal"

So I changed the most basic things to work like they described in the exercise. But the questions specifically mention performance as being an interesting aspect in this assignment. I can however not find anything that stands out (performance is pretty much the same).

If you have any suggestions for what they might have wanted to say during the exercise explanation I would be very happy to hear that.

**Comment by bgrevelt** [comment]
Dude,

How did you test performance difference? I saw a lot of options going into ghci, but I don't know what most of them mean (and yes, I am to lazy to google them right now). If none of those options give you a guarantee that the same sudoku has been generated for both versions of the code, I don't think the comparison makes much sense. I have found that there are huge differences in generation time between different sudoku's. I have seen generation times going up to one minute. 

If you've accounted for that, never mind. Otherwise we might have to try generating a whole bunch of them and doing some statistics one the generation time...

**Comment by Futsy** [comment]
Ehm, benchmarking after the refactor was done by taking a fixed sudoku (one with about a 100 solutions). Then hooking up the profiler and running the solve for both of the versions (the original and the version that had been refactored).

This link shows how to do the profiling: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html

There is also the details I wrote in the file Refactor.hs. It would make sense to test the generating algorithm but since that uses the same function that is being used in the solve I left that out for now. Will try and add results for that.

The profiler shows efficiency in terms of cpu/memory usage which is what I have shown in the file.

**Comment by bgrevelt** [comment]
Ok, if it's about solving and not generation, then my comment isn't that relevant.
